export let dailyQuote = "Love you no matter what!";

let textOrder = 0;

function updateDailyQuote() {
  const quotes = [
    "Love you no matter what!",
    "You make my heart smile every single day.",
    "Forever doesn't seem long enough with you.",
    "You are my greatest adventure.",
    "I choose you, every single day.",
    "You complete me in ways I never knew possible.",
    "My heart is yours, now and always.",
    "You are my safe place.",
    "I fall in love with you more each day.",
    "You are worth every risk I take.",
    "Together, we are unstoppable.",
    "You are my person.",
    "I believe in us.",
    "You make ordinary moments extraordinary.",
    "Life is better with you in it.",
    "You are my favorite hello and my hardest goodbye.",
    "I'm grateful for you every single day.",
    "You bring out the best in me.",
    "I love you more than words can express.",
    "You are my home, no matter where we are.",
    "With you, I feel complete.",
    "You are my greatest blessing.",
    "I trust you with my whole heart.",
    "You are worth fighting for.",
    "I'd choose you in every lifetime.",
    "You make me believe in love again.",
    "You are my forever person.",
    "I'm so proud to call you mine.",
    "Your love changes everything.",
    "You are my happy place.",
    "I never want to stop loving you.",
    "You are my soulmate.",
    "I'm exactly where I need to be with you.",
    "You mean the world to me.",
    "I love every version of you.",
    "You are my greatest treasure.",
    "I'm so lucky to have you.",
    "You are my inspiration.",
    "I believe in our love story.",
    "You make me feel alive.",
    "I'm committed to you and our future.",
    "You are worth every effort.",
    "I love the way you love me.",
    "You are my favorite person in the world.",
    "Together is my favorite place to be.",
    "You make me want to be better.",
    "I'm here for you, always.",
    "You are my sweetest dream come true.",
    "I love you more every day.",
    "You are my forever yes.",
    "I trust the journey we're on together.",
    "You are my greatest love story.",
    "I'm so grateful for you.",
    "You make my life complete.",
    "I love everything about you.",
    "You are my person, forever.",
    "I choose you every single day and always will.",
    "You are my safe haven.",
    "I believe in us completely.",
    "You make life beautiful.",
    "I'm devoted to you and our love.",
    "You are my heart's desire.",
    "I love you with all my soul.",
    "You are my greatest adventure.",
    "I'm so blessed to have you.",
    "You bring joy to my life.",
    "I never want to lose you.",
    "You are my forever home.",
    "I trust you completely.",
    "You are my anchor.",
    "I love the bond we share.",
    "You make every day worth living.",
    "I'm all in with you.",
    "You are my true love.",
    "I believe in our forever.",
    "You are my greatest gift.",
    "I love you unconditionally.",
    "You are my everything.",
    "I'm committed to our love.",
    "You make me so happy.",
    "I adore you completely.",
    "You are my forever person.",
    "I love your smile.",
    "You are my inspiration.",
    "I'm grateful every day for you.",
    "You make my heart race.",
    "I love the way you love me back.",
    "You are my greatest blessing.",
    "I trust you with my heart.",
    "You are my favorite thing.",
    "I love being with you.",
    "You are my safe place.",
    "I believe we're meant to be.",
    "You make me feel loved.",
    "I'm so proud of us.",
    "You are my person.",
    "I love our love story.",
    "You are my greatest treasure.",
    "I'll always choose you.",
    "You make me want to be better.",
    "I love your company.",
    "You are my home.",
    "I'm devoted to you.",
    "You make me feel alive.",
    "I love your presence in my life.",
    "You are my forever.",
    "I believe in our love.",
    "You make my heart full.",
    "I'm so lucky to love you.",
    "You are my greatest joy.",
    "I love you endlessly.",
    "You are my perfect match.",
    "I trust our journey together.",
    "You make life meaningful.",
    "I love every moment with you.",
    "You are my forever home.",
    "I'm in love with you.",
    "You make me so happy.",
    "I believe in us completely.",
    "You are my greatest love.",
    "I love your heart.",
    "You are my person, always.",
    "I'm grateful for your love.",
    "You make my dreams come true.",
    "I love the life we're building.",
    "You are my greatest blessing.",
    "I trust you completely.",
    "You make everything better.",
    "I love being loved by you.",
    "You are my forever yes.",
    "I believe we can overcome anything.",
    "You make me feel secure.",
    "I love your soul.",
    "You are my everything.",
    "I'm committed to our forever.",
    "You make me complete.",
    "I love your love.",
    "You are my greatest adventure.",
    "I believe in what we have.",
    "You make my life beautiful.",
    "I'm so in love with you.",
    "You are my favorite.",
    "I trust our bond.",
    "You make me feel cherished.",
    "I love being your person.",
    "You are my safe haven.",
    "I believe you're the one.",
    "You make my heart sing.",
    "I love your authenticity.",
    "You are my forever.",
    "I'm all yours.",
    "You make me feel at home.",
    "I love our connection.",
    "You are my greatest gift.",
    "I believe in our forever together.",
    "You make everything worthwhile.",
    "I love you always.",
    "You are my person.",
    "I trust you with everything.",
    "You make me feel valued.",
    "I love the bond we share.",
    "You are my forever love.",
    "I'm devoted to you always.",
    "You make my heart full.",
    "I love your presence.",
    "You are my greatest treasure.",
    "I believe you're my soulmate.",
    "You make life worth living.",
    "I love you completely.",
    "You are my favorite person.",
    "I trust our love story.",
    "You make me feel secure.",
    "I love being with you.",
    "You are my forever home.",
    "I'm so grateful for you.",
    "You make me feel loved.",
    "I love your everything.",
    "You are my greatest blessing.",
    "I believe in us.",
    "You make my dreams real.",
    "I love you more daily.",
    "You are my person forever.",
    "I trust you completely.",
    "You make me feel alive.",
    "I love our life together.",
    "You are my safe place.",
    "I'm in love with you completely.",
    "You make my heart smile.",
    "I love your love for me.",
    "You are my forever.",
    "I believe we're meant to be.",
    "You make everything complete.",
    "I love you unconditionally.",
    "You are my greatest love.",
    "I'm committed to our forever.",
    "You make me feel cherished.",
    "I love being loved by you.",
    "You are my favorite.",
    "I trust our bond.",
    "You make my life beautiful.",
    "I love every part of you.",
    "You are my home.",
    "I believe in our love.",
    "You make me so happy.",
    "I love your heart.",
    "You are my person.",
    "I'm grateful for your love.",
    "You make me feel secure.",
    "I love our connection.",
    "You are my greatest gift.",
    "I believe you complete me.",
    "You make my heart full.",
    "I love you always.",
    "You are my forever love.",
    "I trust you fully.",
    "You make me feel valued.",
    "I love being your partner.",
    "You are my safe haven.",
    "I'm devoted to our love.",
    "You make everything better.",
    "I love your soul.",
    "You are my greatest treasure.",
    "I believe in our forever.",
    "You make me feel alive.",
    "I love you deeply.",
    "You are my favorite thing.",
    "I trust our journey.",
    "You make my life meaningful.",
    "I love your presence.",
    "You are my forever home.",
    "I'm in love with you.",
    "You make me feel loved.",
    "I love our story.",
    "You are my person.",
    "I believe in what we have.",
    "You make my heart race.",
    "I love you with all my heart.",
    "You are my greatest blessing.",
    "I'm grateful every day for you.",
    "You make everything worthwhile.",
    "I love being loved by you.",
    "You are my forever.",
    "I trust you with my heart.",
    "You make me feel complete.",
    "I love your authenticity.",
    "You are my greatest love.",
    "I believe you're the one.",
    "You make my life beautiful.",
    "I love you endlessly.",
    "You are my favorite person.",
    "I'm committed to you.",
    "You make me feel secure.",
    "I love our connection.",
    "You are my safe place.",
    "I believe in our future.",
    "You make me so happy.",
    "I love your heart.",
    "You are my everything.",
    "I trust our bond.",
    "You make my dreams real.",
    "I love being with you.",
    "You are my forever home.",
    "I'm so in love with you.",
    "You make me feel valued.",
    "I love your love.",
    "You are my greatest gift.",
    "I believe in us completely.",
    "You make life worth living.",
    "I love you always.",
    "You are my person.",
    "I trust you completely.",
    "You make me feel alive.",
    "I love your presence.",
    "You are my greatest treasure.",
    "I'm devoted to our love.",
    "You make me feel loved.",
    "I love our life together.",
    "You are my forever.",
    "I believe we're perfect together.",
    "You make my heart full.",
    "I love you infinitely.",
    "You are my favorite.",
    "I trust our story.",
    "You make everything complete.",
    "I love your soul.",
    "You are my home.",
    "I'm grateful for you.",
    "You make me feel cherished.",
    "I love being your person.",
    "You are my safe haven.",
    "I believe in our love.",
    "You make my life meaningful.",
    "I love you completely.",
    "You are my greatest blessing.",
    "I'm committed to forever with you.",
    "You make me feel secure.",
    "I love our bond.",
    "You are my forever love.",
  ];

  if (textOrder >= quotes.length) {
    textOrder = 1;
  }
  dailyQuote = quotes[textOrder];
  textOrder++;
}

if (typeof window !== "undefined") {
  setInterval(updateDailyQuote, 24 * 60 * 60 * 1000); // Update every 24 hours
}
updateDailyQuote();
